
name: GenerateDocs

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [generate]
    
jobs:
  generate_job:
    runs-on:  'windows-latest'
    
    steps:
    - name: Checkout configs
      uses: actions/checkout@v3
      with:
        repository: mianalysis/mianalysis.github.io
        ref: main
        
    - name: Get current repo

      uses: actions/checkout@v3

      with:

        repository: mianalysis/mia

        ref: main

        path: .\mia
        
      

    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile
      run: |
          ls
          ls mia
          cd mia
          mvn compile



          rm -r docs
          mkdir docs
          
          echo "temp post compile"
          ls
          echo "docs post compile "
          ls docs


    - name: Run generator with Maven
      run: |
          cd mia
          ls
          mvn exec:java -D"exec.mainClass=io.github.mianalysis.mia.process.documentation.MainGenerator"
      

          ls docs
      

        
    - name: New repo list
      run: |
          ls
          mv docs ..
          cd ..
          rm -r mia
          ls
      
    - name: Add files to repository
      run: |
        git config --global user.name 'Stephen Cross'
        git config --global user.email 'stephencross86@gmail.com'
        git commit -am "Updating documentation"
        git push
