
name: GenerateDocs

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [generate]
    
jobs:
  generate_job:
    runs-on:  'windows-latest'
    
    steps:
    - name: Checkout configs
      uses: actions/checkout@v3
      with:
        repository: mianalysis/mia
        ref: main

    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile
      run: mvn compile

    - name: Remove docs
      run: |
        rm -r docs
        mkdir docs
      
    - name: List dir
      run: ls docs

    - name: Run generator with Maven
      run: mvn exec:java -D"exec.mainClass=io.github.mianalysis.mia.process.documentation.MainGenerator"
      
    - name: List post gen
      run: ls docs
      
    - name: Add files to repository
      run: |
        git config --global user.name 'Stephen Cross'
        git config --global user.email 'stephencross86@gmail.com'
        git commit -am "Updating documentation"
        git push
