
name: GenerateDocs

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [generate]
    
jobs:
  generate_job:
    runs-on:  'windows-latest'
    
    steps:
    - name: Checkout configs
      uses: actions/checkout@v3
      with:
        repository: mianalysis/mia
        ref: main
